Fixed Bugs in Pallet Fragments
fragcolor-xyz/clamor pull request #111
Opened 2022-07-20 14:56 UTC by aang114

Very short PR! 

 - I will only be able to merge the test cases for pallet fragments after this branch is merged

2022-07-20 15:04 UTC, aang114 commented
> Very short PR!
> 
> * I will only be able to merge the test cases for pallet fragments after this branch is merged

only be able to create a PR to merge the test cases for pallet fragments**

2022-07-21 02:49 UTC, sinkingsugar requested changes

2022-07-21 02:49 UTC, sinkingsugar commented on pallets/fragments/src/lib.rs
> +
less spaces

2022-07-21 02:49 UTC, sinkingsugar commented on pallets/fragments/src/lib.rs
> +
relax spaces :)

2022-07-21 03:13 UTC, aang114 commented on pallets/fragments/src/lib.rs
> +
is it better now?

2022-07-21 03:14 UTC, sinkingsugar commented on pallets/fragments/src/lib.rs
> +
yep

2022-07-21 03:15 UTC, sinkingsugar approved these changes
LGTM

2022-07-21 05:21 UTC, merged